name: Run Python
env: 
  URL: ${{ secrets.URL }}
  API_KEY: ${{ secrets.API_KEY }}
  test_subject: ${{ secrets.test_subject }}

on: [push, workflow_dispatch]

jobs:

  pdf:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements_pdf.txt
    - run: python pdf.py
